project:
  type: website
  output-dir: docs

website:
  title: "Pratique du calcul scientifique"
  navbar:
    left:
      - href: poly.qmd
        text: Polycopié
      - href: cours.qmd
        text: Cours magistraux
      - href: notebooks.qmd
        text: Notebooks Jupyter
      - href: devoirs.qmd
        text: Devoirs
      - href: liens.qmd
        text: Liens utiles
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
