project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.ipynb"
  resources:
    - "*.ipynb"

website:
  title: "Pratique du calcul scientifique"
  favicon: "logo_calcul_scientifique.png"
  navbar:
    logo: "logo_calcul_scientifique.png"
    left:
      - href: poly.qmd
        text: Polycopié
      - href: cours.qmd
        text: Cours
      - href: notebooks.qmd
        text: Notebooks
      - href: exam.qmd
        text: Examen
      - href: archives.qmd
        text: Archives
      - href: liens.qmd
        text: Liens utiles
      - href: credits.qmd
        text: Crédits

editor:
    render-on-save: true

format:
  html:
    theme:
      light: default
      dark: darkly
    css: styles.css
    toc: true
