on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v5

      - uses: actions/git-pages@v2
        with:
          site: https://enpc-casc.codeberg.page/
          token: ${{ forge.token }}
          source: docs/
